package org.jahia.modules.npm.modules.engine.rules

// list any import classes here.
import org.jahia.services.content.rules.*
import org.slf4j.Logger

expander rules.dsl

// declare any global variables here
global User user
global Service service
global Logger logger
global JSGlobalObject jsModuleGlobalObject

rule "Npm module - testing rule deployement"
    salience 25
    when
        A property triggerProp has been set on a node
             - the node has the type npmExample:testRule
    then
        Set the property resultProp of the node with the value "It works"
end

rule "Test usage of JS global module object"
    when
>        node: AddedNodeFact ( types contains "jnt:bigText" )
    then
>        jsModuleGlobalObject.call("hello", node);
end