# This workflow trigger a full Sonar analysis at regular interval
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Sonar Analysis - Scheduled

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1,3,5' # At 4AM, on Monday, Wednesday and Friday

jobs:
  sonar-analysis:
    uses: Jahia/jahia-modules-action/.github/workflows/sonar-scan.yml@PIPELINE-76
    secrets: inherit
    # Keeping a matrix since 
    strategy:
      fail-fast: false
      matrix:
         git_branch: ["${{ github.event.repository.default_branch }}"]    
    with:
      module_id: npm-modules-engine
      tests_module_type: npm
      git_branch: ${{ matrix.git_branch }}
